import Link from "next/link";
import { ArrowRight, FileText, Info, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function HomePage() {
  return <main className="min-h-screen overflow-hidden bg-background">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/" className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-primary text-sm font-bold text-primary-foreground">US</span><span><span className="block font-bold">UPTD Kecamatan Sahu</span><span className="block text-xs text-muted-foreground">Layanan Publik Digital</span></span></Link><div className="flex items-center gap-2"><Button variant="ghost" render={<Link href="/login" />}>Masuk</Button><Button render={<Link href="/daftar" />}>Daftar akun <ArrowRight /></Button></div></header>
    <section className="relative mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-16 sm:px-8 sm:pt-24 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div className="absolute -right-24 -top-20 -z-10 size-[28rem] rounded-full bg-primary/5 blur-3xl" /><div><p className="inline-flex items-center gap-2 rounded-full border bg-card px-3 py-1.5 text-xs font-semibold text-primary"><span className="size-2 rounded-full bg-emerald-500" />Pelayanan publik Kecamatan Sahu</p><h1 className="mt-6 max-w-2xl text-4xl font-bold leading-[1.1] tracking-tight sm:text-5xl lg:text-6xl">Layanan publik lebih dekat, <span className="text-primary">mudah diakses.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-muted-foreground">Sampaikan laporan, pantau penanganannya, dan temukan informasi resmi UPTD Kecamatan Sahu dalam satu tempat.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" render={<Link href="/daftar" />}>Mulai gunakan layanan <ArrowRight /></Button><Button size="lg" variant="outline" render={<Link href="/login" />}>Masuk ke akun</Button></div><p className="mt-4 text-xs text-muted-foreground">Untuk masyarakat Kecamatan Sahu · Halmahera Barat</p></div><div className="relative mx-auto w-full max-w-lg"><div className="absolute -inset-4 rounded-[2rem] bg-primary/5" /><div className="relative rounded-[1.6rem] border bg-card p-5 shadow-xl shadow-primary/5 sm:p-7"><div className="flex items-center justify-between border-b pb-4"><div><p className="text-xs text-muted-foreground">Portal layanan</p><p className="mt-1 font-semibold">UPTD Kecamatan Sahu</p></div><span className="rounded-xl bg-primary/10 p-2.5 text-primary"><ShieldCheck className="size-5" /></span></div><div className="mt-5 space-y-3"><div className="flex gap-4 rounded-xl border p-4"><span className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><FileText className="size-5" /></span><div><p className="font-semibold">Pelaporan masyarakat</p><p className="mt-1 text-sm leading-5 text-muted-foreground">Kirim laporan dan ikuti perkembangannya secara transparan.</p></div></div><div className="flex gap-4 rounded-xl border p-4"><span className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-emerald-500/10 text-emerald-700"><Info className="size-5" /></span><div><p className="font-semibold">Informasi layanan</p><p className="mt-1 text-sm leading-5 text-muted-foreground">Akses informasi kantor dan profil wilayah Kecamatan Sahu.</p></div></div></div><div className="mt-5 rounded-xl bg-muted/60 px-4 py-3 text-xs text-muted-foreground">Satu portal resmi untuk mendukung layanan yang responsif dan mudah dijangkau.</div></div></div></section>
    <footer className="border-t bg-muted/30"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-5 py-6 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between sm:px-8"><span>© {new Date().getFullYear()} UPTD Kecamatan Sahu</span><span>Halmahera Barat · Maluku Utara</span></div></footer>
  </main>;
}
